package cl.pojos;
// Generated 30-06-2014 10:39:28 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Comuna generated by hbm2java
 */
public class Comuna  implements java.io.Serializable {


     private int comunaId;
     private Provincia provincia;
     private String comunaNombre;
     private Set<Direccion> direccions = new HashSet<Direccion>(0);

    public Comuna() {
    }

	
    public Comuna(int comunaId) {
        this.comunaId = comunaId;
    }
    public Comuna(int comunaId, Provincia provincia, String comunaNombre, Set<Direccion> direccions) {
       this.comunaId = comunaId;
       this.provincia = provincia;
       this.comunaNombre = comunaNombre;
       this.direccions = direccions;
    }
   
    public int getComunaId() {
        return this.comunaId;
    }
    
    public void setComunaId(int comunaId) {
        this.comunaId = comunaId;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getComunaNombre() {
        return this.comunaNombre;
    }
    
    public void setComunaNombre(String comunaNombre) {
        this.comunaNombre = comunaNombre;
    }
    public Set<Direccion> getDireccions() {
        return this.direccions;
    }
    
    public void setDireccions(Set<Direccion> direccions) {
        this.direccions = direccions;
    }




}


