package cl.pojos;
// Generated 30-06-2014 10:39:28 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Direccion generated by hbm2java
 */
public class Direccion  implements java.io.Serializable {


     private Integer direccionId;
     private Region region;
     private Provincia provincia;
     private Comuna comuna;
     private String calle;
     private Set<Estudiante> estudiantes = new HashSet<Estudiante>(0);
     private Set<Tutor> tutors = new HashSet<Tutor>(0);

    public Direccion() {
    }

	
    public Direccion(Region region, Provincia provincia, Comuna comuna, String calle) {
        this.region = region;
        this.provincia = provincia;
        this.comuna = comuna;
        this.calle = calle;
    }
    public Direccion(Region region, Provincia provincia, Comuna comuna, String calle, Set<Estudiante> estudiantes, Set<Tutor> tutors) {
       this.region = region;
       this.provincia = provincia;
       this.comuna = comuna;
       this.calle = calle;
       this.estudiantes = estudiantes;
       this.tutors = tutors;
    }
   
    public Integer getDireccionId() {
        return this.direccionId;
    }
    
    public void setDireccionId(Integer direccionId) {
        this.direccionId = direccionId;
    }
    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public Comuna getComuna() {
        return this.comuna;
    }
    
    public void setComuna(Comuna comuna) {
        this.comuna = comuna;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public Set<Estudiante> getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set<Estudiante> estudiantes) {
        this.estudiantes = estudiantes;
    }
    public Set<Tutor> getTutors() {
        return this.tutors;
    }
    
    public void setTutors(Set<Tutor> tutors) {
        this.tutors = tutors;
    }




}


