package cl.pojos;
// Generated 30-06-2014 10:39:28 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia  implements java.io.Serializable {


     private int provinciaId;
     private Region region;
     private String provinciaNombre;
     private Set<Direccion> direccions = new HashSet<Direccion>(0);
     private Set<Comuna> comunas = new HashSet<Comuna>(0);

    public Provincia() {
    }

	
    public Provincia(int provinciaId) {
        this.provinciaId = provinciaId;
    }
    public Provincia(int provinciaId, Region region, String provinciaNombre, Set<Direccion> direccions, Set<Comuna> comunas) {
       this.provinciaId = provinciaId;
       this.region = region;
       this.provinciaNombre = provinciaNombre;
       this.direccions = direccions;
       this.comunas = comunas;
    }
   
    public int getProvinciaId() {
        return this.provinciaId;
    }
    
    public void setProvinciaId(int provinciaId) {
        this.provinciaId = provinciaId;
    }
    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }
    public String getProvinciaNombre() {
        return this.provinciaNombre;
    }
    
    public void setProvinciaNombre(String provinciaNombre) {
        this.provinciaNombre = provinciaNombre;
    }
    public Set<Direccion> getDireccions() {
        return this.direccions;
    }
    
    public void setDireccions(Set<Direccion> direccions) {
        this.direccions = direccions;
    }
    public Set<Comuna> getComunas() {
        return this.comunas;
    }
    
    public void setComunas(Set<Comuna> comunas) {
        this.comunas = comunas;
    }




}


