package cl.pojos;
// Generated 30-06-2014 10:39:28 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Region generated by hbm2java
 */
public class Region  implements java.io.Serializable {


     private int regionId;
     private String regionNombre;
     private Set<Provincia> provincias = new HashSet<Provincia>(0);
     private Set<Direccion> direccions = new HashSet<Direccion>(0);

    public Region() {
    }

	
    public Region(int regionId) {
        this.regionId = regionId;
    }
    public Region(int regionId, String regionNombre, Set<Provincia> provincias, Set<Direccion> direccions) {
       this.regionId = regionId;
       this.regionNombre = regionNombre;
       this.provincias = provincias;
       this.direccions = direccions;
    }
   
    public int getRegionId() {
        return this.regionId;
    }
    
    public void setRegionId(int regionId) {
        this.regionId = regionId;
    }
    public String getRegionNombre() {
        return this.regionNombre;
    }
    
    public void setRegionNombre(String regionNombre) {
        this.regionNombre = regionNombre;
    }
    public Set<Provincia> getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Set<Provincia> provincias) {
        this.provincias = provincias;
    }
    public Set<Direccion> getDireccions() {
        return this.direccions;
    }
    
    public void setDireccions(Set<Direccion> direccions) {
        this.direccions = direccions;
    }




}


